name: SAST - Dependencies
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: Install and build javascript
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - name: Create SBOM with CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@v1
        with: 
          output: './test.app.bom.xml'
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: './test.app.bom.xml'
      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: './'
      - name: Display contents of SBOM artifact
        run: |
          cat ./test.app.bom.xml
