name: Checkov IAC Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

      - name: Test with Checkov
        id: checkov
        run: |
          checkov -d . | tee checkov-output.txt
          echo '::set-output name=checkov-output::$(cat checkov-output.txt)'

      - name: Upload Checkov Output Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: checkov-output
          path: checkov-output.txt

      - name: Show Checkov Results
        if: ${{ steps.checkov.outcome == 'success' }}
        run: |
          echo "${{ steps.checkov.outputs.checkov-output }}"

