name: Checkov IAC Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Checkov
        run: |
          python3 -m pip install --upgrade pip
          pip3 install checkov

      - name: Test with Checkov
        id: checkov
        run: |
          checkov -d . > checkov-results.txt

      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results.txt

