name: SAST - Dependecies - SBOM - GO
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Install and build Go
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Download cyclonedx-gomod
        uses: CycloneDX/gh-gomod-generate-sbom@v1
        with:
          version: v1
      - name: Generate SBOM
        run: cyclonedx-gomod app -output test.app.bom.xml 
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: './test.app.bom.xml'
      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: './'
      - name: Display contents of SBOM artifact
        run: |
          cat ./test.app.bom.xml
