name: SAST - Dependecies - SBOMB - GO
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Install and build Go
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install CycloneDX tool
        run: |
          curl -L https://github.com/CycloneDX/cyclonedx-go/releases/download/v0.7.0/cyclonedx-go-0.7.0.tar.gz | tar xz -C /tmp/
          ls -la /tmp/
          sudo mv /tmp/cyclonedx-go /usr/local/bin/
      - name: Build application
        run: go build -o app
      - name: Create SBOM with CycloneDX
        run: cyclonedx-go -o test.app.bom.xml
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: './test.app.bom.xml'
      - name: Download SBOM artifact
        uses: actions/download-artifact@v2
        with:
          name: sbom
          path: './'
      - name: Display contents of SBOM artifact
        run: |
          cat ./test.app.bom.xml

